---
#- name: repo configuration
#  hosts: all
#  gather_facts: false
#  become: true
#  tasks:
#  - name: enable repo
#    template:
#      src: /etc/yum.repos.d/open_three-tier-app.repo
#      dest: /etc/yum.repos.d/open_three-tier-app.repo
#      mode: 0644

- hosts: all
  become: yes
  roles:
    - common

- hosts: apps
  gather_facts: false
  become: yes
  roles:
    - app-tier

- hosts: frontends
  gather_facts: false
  become: yes
  roles:
    - lb-tier

- hosts: appdbs
  gather_facts: false
  become: yes
  roles:
    - db-tier

